apiVersion: v1
kind: Service
metadata:
  name: {{ template "pull-request-size.fullname" . }}
  labels:
{{ include "pull-request-size.labels" . |indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ template "pull-request-size.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
